In [1]:
import joblib
import numpy as np

In [2]:
model_DT = joblib.load('models/Heart_DT.pkl')
model_GB = joblib.load('models/Heart_GB.pkl')
model_KNN = joblib.load('models/Heart_KNN.pkl')
model_LR = joblib.load('models/Heart_LR.pkl')
model_RFC = joblib.load('models/Heart_RFC.pkl')
model_SVM = joblib.load('models/Heart_SVM.pkl')

In [3]:
input_arr = np.array([1, 39, 0,	8, 0, 0, 1,	0, 236, 106.0, 70.0, 26.0, 76, 82]).reshape(1, -1)	

In [4]:
def predict(input, model):
    return model.predict(input)

def predict_proba(input, model):
    return model.predict_proba(input)

In [5]:
res_DT = predict(input_arr, model_DT)
print(res_DT)

res_DT_proba = predict_proba(input_arr, model_DT)
print(res_DT_proba)

[1]
[[0. 1.]]


In [6]:
res_GB = predict(input_arr, model_GB)
print(res_GB)

res_GB_proba = predict_proba(input_arr, model_GB)
print(res_GB_proba)

[1]
[[2.15188047e-05 9.99978481e-01]]


In [7]:
res_KNN = predict(input_arr, model_KNN)
print(res_KNN)

res_KNN_proba = predict_proba(input_arr, model_KNN)
print(res_KNN_proba)

[1]
[[0. 1.]]


In [8]:
res_LR = predict(input_arr, model_LR)
print(res_LR)

res_LR_proba = predict_proba(input_arr, model_LR)
print(res_LR_proba)

[1]
[[4.55635529e-12 1.00000000e+00]]


In [9]:
res_RFC = predict(input_arr, model_RFC)
print(res_RFC)

res_RFC_proba = predict_proba(input_arr, model_RFC)
print(res_RFC_proba)

[1]
[[0.02 0.98]]


In [10]:
res_SVM = predict(input_arr, model_SVM)
print(res_SVM)

#res_SVM_proba = predict_proba(input_arr, model_SVM)
#print(res_SVM_proba)

[1]


In [11]:
ensemble_result = [res_DT_proba[0], res_GB_proba[0], res_KNN_proba[0], res_LR_proba[0], res_RFC_proba[0]]
print(ensemble_result)

[array([0., 1.]), array([2.15188047e-05, 9.99978481e-01]), array([0., 1.]), array([4.55635529e-12, 1.00000000e+00]), array([0.02, 0.98])]


In [12]:
output = np.mean(ensemble_result, axis = 0)
print(output)

print('Final Prediction - Class {}'.format(output.argmax()))

[0.0040043 0.9959957]
Final Prediction - Class 1
